global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingest-service'
    static_configs:
      - targets: ['ingest-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'llm-manager'
    static_configs:
      - targets: ['llm-manager:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'email-processor'
    static_configs:
      - targets: ['email-processor:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'otrs-integration'
    static_configs:
      - targets: ['otrs-integration:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'backup-service'
    static_configs:
      - targets: ['backup-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'paperless'
    static_configs:
      - targets: ['paperless:8010']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  - job_name: 'admin-dashboard'
    static_configs:
      - targets: ['admin-dashboard:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s 