global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ingest Service
  - job_name: 'ingest-service'
    static_configs:
      - targets: ['cas-ingest-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # MinIO (if using minio_exporter)
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']

  # RabbitMQ (if using rabbitmq_exporter)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Node Exporter (for system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 