apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-service
  namespace: cas-system
  labels:
    app: ingest-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingest-service
  template:
    metadata:
      labels:
        app: ingest-service
    spec:
      containers:
      - name: ingest-service
        image: cas_stm-ingest-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cas-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cas-secrets
              key: minio-secret-key
        - name: RABBITMQ_URL
          value: "amqp://cas_user:cas_password@rabbitmq:5672/"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        - name: LOG_LEVEL
          value: "INFO"
        - name: NAS_SOURCE_PATH
          value: "/mnt/nas/source"
        - name: NAS_PROCESSED_PATH
          value: "/mnt/nas/processed"
        - name: FOOTAGE_PATH
          value: "/mnt/footage"
        volumeMounts:
        - name: nas-share
          mountPath: /mnt/nas
          readOnly: false
        - name: footage-share
          mountPath: /mnt/footage
          readOnly: false
        - name: sorting-rules
          mountPath: /app/config/sorting-rules.yaml
          subPath: sorting-rules.yaml
        - name: processed-data
          mountPath: /data/sorted
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nas-share
        persistentVolumeClaim:
          claimName: nas-share-pvc
      - name: footage-share
        persistentVolumeClaim:
          claimName: footage-share-pvc
      - name: sorting-rules
        configMap:
          name: sorting-rules-config
      - name: processed-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: cas-system
spec:
  selector:
    app: ingest-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cas-ingest-service-hpa
  namespace: cas-dms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cas-ingest-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60 