apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-share-pv
  labels:
    type: nas-share
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100  # NAS Server IP
    path: /volume1/documents
  mountOptions:
    - nolock
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-share-pvc
  namespace: cas-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      type: nas-share
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: footage-share-pv
  labels:
    type: footage-share
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100  # NAS Server IP
    path: /volume1/footage
  mountOptions:
    - nolock
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: footage-share-pvc
  namespace: cas-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  selector:
    matchLabels:
      type: footage-share 