apiVersion: v1
kind: PersistentVolume
metadata:
  name: cas-nas-pv
  labels:
    type: nas-storage
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100  # NAS Server IP
    path: /mnt/nas/cas-data
  mountOptions:
    - nolock
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cas-nas-pvc
  namespace: cas-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      type: nas-storage
---
# Local Development NAS Mount
apiVersion: v1
kind: ConfigMap
metadata:
  name: cas-nas-config
  namespace: cas-system
data:
  nas-mount.sh: |
    #!/bin/bash
    # NAS Mount Script for Local Development
    
    NAS_SERVER="192.168.1.100"
    NAS_PATH="/mnt/nas/cas-data"
    LOCAL_MOUNT="/mnt/nas"
    
    # Create mount directory
    sudo mkdir -p $LOCAL_MOUNT
    
    # Mount NAS share
    sudo mount -t nfs $NAS_SERVER:$NAS_PATH $LOCAL_MOUNT
    
    # Set permissions
    sudo chown -R 1000:1000 $LOCAL_MOUNT
    
    echo "NAS mounted successfully at $LOCAL_MOUNT" 