# API Gateway RBAC Configuration

roles:
  admin:
    description: Full access to all endpoints
  user:
    description: Standard access to read and limited write operations

permissions:
  ingest:
    GET:
      paths:
        - "processing/**"
        - "classification/pending"
        - "classification/download"
        - "duplicates"
        - "duplicates/**"
        - "crawler/**"
        - "config/**"
      roles: ["admin", "user"]
    POST:
      paths:
        - "processing/start"
        - "upload"
        - "processing/rollback/*"
        - "classification/confirm"
        - "duplicates/**"
        - "crawler/**"
        - "config/**"
      roles: ["admin"]
  email:
    GET:
      paths:
        - "health"
      roles: ["admin", "user"]
    POST:
      paths:
        - "process/*"
      roles: ["admin"]
  footage:
    GET:
      paths:
        - "files/**"
        - "statistics"
      roles: ["admin", "user"]
    POST:
      paths:
        - "upload"
        - "search"
      roles: ["admin", "user"]
    DELETE:
      paths:
        - "files/*"
      roles: ["admin"]
  llm:
    GET:
      paths:
        - "models"
        - "health"
      roles: ["admin", "user"]
    POST:
      paths:
        - "models/pull"
        - "classify"
      roles: ["admin"]
    DELETE:
      paths:
        - "models/*"
      roles: ["admin"]
  otrs:
    GET:
      paths:
        - "tickets"
        - "tickets/*"
        - "attachments/*"
      roles: ["admin", "user"]
    POST:
      paths:
        - "export"
      roles: ["admin"]
  backup:
    GET:
      paths:
        - "health"
        - "backups"
        - "backups/*"
      roles: ["admin"]
    POST:
      paths:
        - "backup"
        - "backups/*/restore"
        - "cleanup"
      roles: ["admin"]
    DELETE:
      paths:
        - "backups/*"
      roles: ["admin"]
  storage:
    GET:
      paths:
        - "health"
      roles: ["admin", "user"]
    POST:
      paths:
        - "detect"
        - "test"
        - "list"
        - "download"
      roles: ["admin", "user"]
  metrics:
    GET:
      paths:
        - "api/metrics/**"
      roles: ["admin", "user"]
  users:
    GET:
      paths:
        - "users/**"
      roles: ["admin"]
